### ISSUE TITLE
node v6.9.4 При запуске webpack -w ошибки

### ISSUE THREAD

**Issue by Fi1osof** [proxyfabio/MODX.ShopModxBoxFrontend#2]
```
ERROR in ./src/entries/app.js
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
```

node v0.10.48 все ОК работает.

**Comment by rogaldh** [comment]
Без способов получения данной ошибки тикет будет не полон.
Запуск происходит на модифицированном контенте? Если да — код `app.js` в студию.

**Comment by Fi1osof** [comment]
Просто поставил ноду 6.9.4 на убунту 14-ую и все, выполняю webpack -w - ошибка.

**Comment by rogaldh** [comment]
Потестирую — отпишусь. Займет время.

**Comment by Fi1osof** [comment]
ОК. Спасибо.

**Comment by Fi1osof** [comment]
@proxyfabio ругается вот на это: https://github.com/MODX-Club/modx-shopmodx-frontend/blob/master/webpack.config.js#L50-L52
Если удалить этот блок, то запускается.

**Comment by Fi1osof** [comment]
Все, закрываю. Надо было просто версии бабела обновить. https://github.com/MODX-Club/modx-shopmodx-frontend/commit/16a6fe1b68e66199b01e29dc71a7e94192742fe7
